
valid_name_1 = 'Иван'
valid_name_2 = 'Ivan'
valid_name_3 = 'иван'
valid_name_4 = 'ivan'
valid_email = 'ivanov@yandex.ru'
valid_phone = '93155555555'
valid_company = 'Only.digital'
invalid_name_1 = ' '
invalid_name_2 = ''
invalid_name_3 = '@#$$%^'
about_project = 'Only.digital прекрасная компания,\n в которой работают над крутыми проектами и решают интересные задачи.\n Я хочу в ней работать!!!'
